package ridl.codegen.kotlin.types

import ridl.codegen.kotlin.Options
import ridl.codegen.kotlin.PLUGIN
import ridl.codegen.v1.ModelOuterClass.Interface
import ridl.codegen.v1.ModelOuterClass.Model

/**
 * The AIDL binding of the frame (frame specification §11.2, docs/design.md
 * §5), from templates rather than KotlinPoet (D-K2): per declared interface,
 * `aidl/<package path>/I<Iface>.aidl` and `I<Iface>Listener.aidl`, and the
 * three parcelables every package shares under `aidl/ridl/rt/`.
 *
 * The generated interface carries the frame, not a typed method per payload
 * (D-K7): a call's arguments and a query's reply cross as a `Frame` whose
 * payload is the FlatBuffers bytes `Codec.kt` writes.
 *
 * **Where the codes are.** The frame specification fixes a call's AIDL method
 * code as its ordinal. docs/design.md §5 puts the control plane on codes 1 to
 * 4 and also on "the four codes below the interface's lowest ordinal", which
 * disagree, and either collides with a call whose ordinal is 1 to 4 — cabin's
 * `setLevel` is 3. So the control plane is on the four highest codes AIDL
 * admits, [ATTACH] to [READ], where no ordinal of a real interface reaches,
 * and an interface with a call at or past [ATTACH] is refused.
 */
class AidlEmitter(private val model: Model, private val options: Options) {
    class File(val path: String, val text: String)

    private val pkg = options.kotlinPackage

    /**
     * The files for the interfaces named in [faced], and for each of them the
     * AIDL cannot carry, a warning naming it. An interface with no face gets
     * no AIDL: the binding is built over the face, as the Rust descriptors and
     * face stand or fall together.
     */
    fun emit(faced: Set<String>? = null): Pair<List<File>, List<String>> {
        val files = mutableListOf<File>()
        val warnings = mutableListOf<String>()
        val dir = "aidl/" + pkg.replace('.', '/')
        for (iface in model.interfacesList.filter { it.hasDeclared() && (faced == null || it.declared.declared in faced) }) {
            val name = iface.declared.camel
            try {
                files += File("$dir/I$name.aidl", service(iface))
                files += File("$dir/I${name}Listener.aidl", listener(name))
            } catch (refusal: Refusal) {
                warnings += "$PLUGIN: interface `${model.name.dotted}.${iface.declared.declared}` has no AIDL: ${refusal.message}"
            }
        }
        if (files.isNotEmpty()) {
            files += File("aidl/ridl/rt/Frame.aidl", FRAME)
            files += File("aidl/ridl/rt/Outcome.aidl", OUTCOME)
            files += File("aidl/ridl/rt/CatalogRef.aidl", CATALOG_REF)
        }
        return files to warnings
    }

    private fun header(): String = "// Generated by $PLUGIN from `${model.name.dotted}`. Do not edit.\n"

    private fun service(iface: Interface): String {
        val name = iface.declared.camel
        if (iface.number.toLong() and 0xFFFF_FFFFL > LAST_CALL_TRANSACTION) {
            refuse("its number ${iface.number} is past Binder's LAST_CALL_TRANSACTION")
        }
        val calls = iface.slotsList.filter { it.hasInteraction() && (it.interaction.hasCommand() || it.interaction.hasQuery()) }
        val methods = calls.joinToString("") { slot ->
            if (slot.ordinal >= ATTACH) refuse("call `${slot.interaction.name.declared}` has ordinal ${slot.ordinal}, where the control plane is")
            val method = slot.interaction.name.camel.replaceFirstChar(Char::lowercaseChar)
            if (slot.interaction.hasCommand()) {
                "\n    /** Command `${slot.interaction.name.declared}`, acknowledged through the listener's `onAck`. */\n" +
                    "    oneway void $method(in Frame args) = ${slot.ordinal};\n"
            } else {
                "\n    /** Query `${slot.interaction.name.declared}`: the reply frame, or the binding's exception for a contract error. */\n" +
                    "    Frame $method(in Frame args) = ${slot.ordinal};\n"
            }
        }
        return header() + """
            |package $pkg;
            |
            |import ridl.rt.CatalogRef;
            |import ridl.rt.Frame;
            |import ridl.rt.Outcome;
            |import $pkg.I${name}Listener;
            |
            |/**
            | * Interface `${iface.declared.declared}` of `${model.name.dotted}`, number ${iface.number}, bound to the
            | * ridl frame (frame specification §11.2). A call's method code is its ordinal;
            | * the control plane is on the four highest codes AIDL admits.
            | */
            |interface I$name {
            |    /** Opens the session: `accepted`, or `refused` with the reason (§6.1). */
            |    Outcome attach(in CatalogRef catalog, int frameVersion, int encoding) = $ATTACH;
            |
            |    /** Starts delivery of the listed signals and events to [listener] (§6.2). */
            |    Outcome subscribe(in int[] ordinals, I${name}Listener listener) = $SUBSCRIBE;
            |
            |    /** Stops delivery of the listed signals and events to [listener] (§6.2). */
            |    Outcome unsubscribe(in int[] ordinals, I${name}Listener listener) = $UNSUBSCRIBE;
            |
            |    /** The current state of one signal, or the value of one `fixed`, as a `publish` frame (§6.3). */
            |    Frame read(int ordinal) = $READ;
            |$methods}
            |""".trimMargin()
    }

    private fun listener(name: String): String = header() + """
        |package $pkg;
        |
        |import ridl.rt.Frame;
        |import ridl.rt.Outcome;
        |
        |/** What a consumer of `I$name` registers with `subscribe`: the provider's side of the data plane. */
        |oneway interface I${name}Listener {
        |    /** One `publish` of a signal's state (§5.1). */
        |    void onSignal(in Frame frame);
        |
        |    /** One `occurrence` of an event (§5.2). */
        |    void onEvent(in Frame frame);
        |
        |    /** A command's `response`: its acknowledgment (§5.3). */
        |    void onAck(long correlation, in Outcome outcome);
        |}
        |""".trimMargin()

    companion object {
        /** Binder's `LAST_CALL_TRANSACTION`: no code past it is a call. */
        const val LAST_CALL_TRANSACTION: Long = 0x00FF_FFFF

        /** The highest method id the `aidl` tool admits: it reserves the codes above for its meta-transactions. */
        const val MAX_AIDL_ID: Int = 16_777_114

        const val ATTACH: Int = MAX_AIDL_ID - 3
        const val SUBSCRIBE: Int = MAX_AIDL_ID - 2
        const val UNSUBSCRIBE: Int = MAX_AIDL_ID - 1
        const val READ: Int = MAX_AIDL_ID

        private val FRAME = """
            |// Generated by $PLUGIN. The same for every package. Do not edit.
            |package ridl.rt;
            |
            |/**
            | * One frame of the ridl frame specification §4 on the data plane: the header
            | * and the payload, in the session's encoding. An `InterfaceNo`, an `Ordinal`
            | * and a `u64` are carried in the signed field of their width, bit for bit.
            | */
            |parcelable Frame {
            |    /** `InterfaceNo`, never 0. */
            |    int iface;
            |    /** `Ordinal`, never 0. */
            |    int ordinal;
            |    /** `Kind`, 1 to 5. */
            |    byte kind;
            |    /** The envelope's `stamp`: microseconds since the PTP epoch, TAI. */
            |    long stamp;
            |    /** The envelope's `seq`. */
            |    long seq;
            |    /** On a `publish` only: 1 `Init`, 2 `Live`, 3 `Invalid(Declared)`; 0 elsewhere. */
            |    byte provenance;
            |    /** On a `response` only: the `seq` of the request answered; 0 elsewhere. */
            |    long correlation;
            |    /** The payload bytes, empty where the form carries none (§5.6). */
            |    byte[] payload;
            |}
            |""".trimMargin()

        private val OUTCOME = """
            |// Generated by $PLUGIN. The same for every package. Do not edit.
            |package ridl.rt;
            |
            |/**
            | * The `outcome` of the ridl frame specification: of a `response` (§5.3, §5.4),
            | * of `attached` (§6.1) and of an `answer` (§6.2).
            | */
            |parcelable Outcome {
            |    /** 1 `accepted`, 2 `reply`, 3 `contract`, 4 `corrupt`, 5 `refused`. */
            |    byte status;
            |    /**
            |     * Under `contract`: 1 `InvalidValue`, 2 `PreconditionFailed`,
            |     * 3 `ContractBroken`, 4 `UnknownInteraction`.
            |     */
            |    byte contract;
            |    /** Under `InvalidValue`: the violated type's name. */
            |    @nullable String typeName;
            |    /** Under `InvalidValue`: 1 `Range`, 2 `Step`, 3 `Length`, 4 `Pattern`, 5 `Variant`. */
            |    byte rule;
            |    /**
            |     * Under `refused`: 1 `unknown_catalog`, 2 `catalog_mismatch`,
            |     * 3 `encoding_unsupported`, 4 `frame_version_unsupported`, 5 `range`.
            |     */
            |    byte reason;
            |}
            |""".trimMargin()

        private val CATALOG_REF = """
            |// Generated by $PLUGIN. The same for every package. Do not edit.
            |package ridl.rt;
            |
            |/** A catalog: one package's name and its 32-byte catalog hash (§6.1). */
            |parcelable CatalogRef {
            |    String name;
            |    byte[] hash;
            |}
            |""".trimMargin()
    }
}
